import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import Header from '@/components/common/Header'
import MobileHeader from '@/components/common/MobileHeader'
import NavigationBar from '@/components/common/NavigationBar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <MobileHeader />
        <div className={'sm:pt-20 lg:pt-20 xl:pt-20 '}>
          <main>{children}</main>
          <NavigationBar />
        </div>
      </body>
    </html>
  )
}
