import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import BackgroundLayout from '@/commons/components/common/BackgroundLayout'
import ClientAppWrapper from '@/commons/components/common/ClientAppWrapper'
import Header from '@/commons/components/common/Header'
import NavigationBar from '@/commons/components/common/NavigationBar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Shoong',
  description: 'Generated by create next app',
  icons: {
    icon: '/logos/shoong-logo.svg',
  },
}

// 기본 Next.js 레이아웃 타입 사용
interface RootLayoutProps {
  children: React.ReactNode
  params?: Promise<any>
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BackgroundLayout>
          <Header />
          <ClientAppWrapper>
            <div className={''}>
              <main className={'mb-15 '}>{children}</main>
              <NavigationBar />
            </div>
          </ClientAppWrapper>
        </BackgroundLayout>
      </body>
    </html>
  )
}
