import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import BackgroundLayout from '@/commons/components/common/BackgroundLayout'
import Header from '@/commons/components/common/Header'
import MobileHeader from '@/commons/components/common/MobileHeader'
import NavigationBar from '@/commons/components/common/NavigationBar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BackgroundLayout>
          <Header />
          <MobileHeader />
          <div className={''}>
            <main className={'mb-20'}>{children}</main>
            <NavigationBar />
          </div>
        </BackgroundLayout>
      </body>
    </html>
  )
}
